#!/usr/bin/env python3
"""Generate Deep North gear's personal Fader-key list from a native ObjectDB dump.

Capture after mod registration and enforced configuration. Material biome overrides
cite native evidence; amounts are Recipe.Requirement.GetAmount(quality). Finished
foundry gear and its recipe intermediates both belong in the list. Baits, herbs,
food and other non-gear goods do not. Raw dumps remain with boot evidence, not git.
"""
import argparse
import hashlib
import json
from pathlib import Path

BIOMES = {key: biome for key, biome in zip(
    ("", "defeated_eikthyr", "defeated_gdking", "defeated_bonemass",
     "defeated_dragon", "defeated_goblinking", "defeated_queen", "defeated_fader"),
    ("Meadows", "BlackForest", "Swamp", "Mountain", "Plains", "Mistlands", "AshLands", "DeepNorth"))}
GEAR = {"OneHandedWeapon", "TwoHandedWeapon", "TwoHandedWeaponLeft", "Bow",
        "Shield", "Helmet", "Chest", "Legs", "Shoulder"}
# WAP 1.0.0 knows no native Deep North materials. Keep native provenance here.
DEEP_NORTH_MATERIALS = {
    "MooseHide": ("DeepNorth", "dump spawns[Moose].biome=DeepNorth; drops[Moose]"),
    "MooseSinew": ("DeepNorth", "dump spawns[Moose].biome=DeepNorth; drops[Moose]"),
    "MooseMeat": ("DeepNorth", "dump spawns[Moose].biome=DeepNorth; drops[Moose]"),
    "TrophyMoose": ("DeepNorth", "dump spawns[Moose].biome=DeepNorth; drops[Moose]"),
    "SealHide": ("DeepNorth", "dump spawns[Seal].biome=DeepNorth; drops[Seal]"),
    "SealBlubber": ("DeepNorth", "dump spawns[Seal].biome=DeepNorth; drops[Seal]"),
    "NornThread": ("DeepNorth", "dump spawns[JotunWitch].biome=DeepNorth; drops[JotunWitch]"),
    "ElakingHairBundle": ("DeepNorth", "dump spawns[Elaking].biome=DeepNorth; drops[Elaking]"),
    "BarkaBranch": ("DeepNorth", "dump spawns[Barka].biome=DeepNorth; drops[Barka]"),
    "Gold": ("DeepNorth", "dump locations[DN_gammeltrollFrac01].biome=DeepNorth contains TrollFrost_Frac_legs; materialSources[TrollFrost_Frac_legs].MineRock5.m_dropItems=GoldOre; DataForge/pieces.reference.yml:374 GoldOre -> Gold"),
    "Frostwood": ("DeepNorth", "dump vegetation[FirTree_oldLog_deepnorth].biome=DeepNorth; materialSources[FirTree_oldLog_deepnorth].DropOnDestroyed=Frostwood"),
    "Ice": ("DeepNorth", "dump vegetation[ice1].biome=DeepNorth; materialSources[ice1].DropOnDestroyed=Ice"),
    "Kale": ("DeepNorth", "dump vegetation[Pickable_SeedKale].biome=DeepNorth; pickables[Pickable_SeedKale].item=KaleSeeds; plants[sapling_Kale].grown=Pickable_Kale; pickables[Pickable_Kale].item=Kale"),
    "Lingonberry": ("DeepNorth", "dump vegetation[LingonberryBush].biome=DeepNorth; pickables[LingonberryBush].item=Lingonberry"),
    "SpiceDeepNorth": ("DeepNorth", "dump traders[BogWitch].items[SpiceDeepNorth].key=defeated_frozenking_p3 (Deep North boss)"),
}


def material_biomes(data):
    result = {}
    for mapping in data["maps"].values():
        for material, key in mapping.items():
            result.setdefault(material, set()).add(BIOMES[key])
    for material, (biome, _) in DEEP_NORTH_MATERIALS.items():
        result.setdefault(material, set()).add(biome)
    return result


def needs_fader(recipe, biomes):
    # WAP semantics: any accessible alternative suffices; all positive costs
    # otherwise apply. Check upgrades as well as the initial craft.
    for quality in range(recipe["maxQuality"]):
        costs = ["DeepNorth" in biomes.get(resource["prefab"], set())
                 for resource in recipe["resources"] if resource["amounts"][quality] > 0]
        if costs and (all(costs) if recipe["onlyOne"] else any(costs)):
            return True
    return False


def generate(data):
    biomes = material_biomes(data)
    conversions = {}
    for conversion in data["conversions"]:
        if data["itemTypes"].get(conversion["output"]) in GEAR:
            conversions.setdefault(conversion["input"], set()).add(conversion["output"])
    items = set()
    for recipe in data["recipes"]:
        gear = recipe["itemType"] in GEAR and not (
            recipe["itemType"] == "OneHandedWeapon" and recipe["skill"] == "None")
        outputs = conversions.get(recipe["prefab"], set())
        if (gear or outputs) and needs_fader(recipe, biomes):
            items.add(recipe["prefab"])
            items.update(outputs)
    return sorted(items)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dump", type=Path)
    parser.add_argument("--output", type=Path,
                        default=Path("config/enforced/lembitu.callings.deep-north.txt"))
    args = parser.parse_args()
    raw = args.dump.read_bytes()
    items = generate(json.loads(raw))
    lines = ["# Generated by scripts/generate-ladder.py; do not edit.",
             "# Deep North gear and Frost Foundry intermediates require the personal Fader key.",
             "# Native dump SHA-256: " + hashlib.sha256(raw).hexdigest(), *items]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")
    print(json.dumps({"output": str(args.output), "total": len(items)}))


if __name__ == "__main__":
    main()
