#!/usr/bin/env python3
"""Write ServerManager's discord.yml from the Discord layout's IDs and webhook routes.

Routes and channels follow docs/wiki/discord.md. Inputs, both private files on astral-bicep:
~/.config/lembitu/discord.env (IDs, from scripts/wizard-discord.sh and scripts/discord-layout.sh)
and ~/.config/lembitu/discord-webhooks.env (route URLs). The bot token is not written here:
ServerManager reads SERVERMANAGER_DISCORD_BOT_TOKEN from the container environment.

Usage: servermanager-discord.py <ServerManager store dir>. The file is replaced atomically, 0600.
"""
import json
import os
import pathlib
import sys

CONFIG = pathlib.Path(os.environ.get('LEMBITU_DISCORD_CONFIG', pathlib.Path.home() / '.config/lembitu'))

# route -> ServerManager events, per the layout table in docs/wiki/discord.md
ROUTES = {
    'STATUS': ['server.status', 'server.announcement'],
    'ACTIVITY': ['player.connection', 'player.death', 'boss.killed', 'raid.status'],
    'CHAT': ['chat.shout'],
    'ADMIN_ALERTS': ['security.alert', 'security.admin_bypass', 'character.validation',
                     'character.shadow_stalled', 'character.revision_observed', 'connection.rejected',
                     'moderation.action', 'command.executed', 'cron.executed'],
}
NAMES = {'STATUS': 'Server status', 'ACTIVITY': 'Activity', 'CHAT': 'Chat', 'ADMIN_ALERTS': 'Admin alerts'}


def read_env(path):
    values = {}
    for line in path.read_text().splitlines():
        if '=' in line and not line.lstrip().startswith('#'):
            key, value = line.split('=', 1)
            values[key.strip()] = value.strip()
    return values


def snowflake(ids, key):
    value = ids.get(key, '')
    if not (value.isdigit() and 17 <= len(value) <= 20):
        raise SystemExit(f'{key} is missing from discord.env; run scripts/discord-layout.sh apply and copy it here')
    return int(value)


def main():
    if len(sys.argv) != 2:
        raise SystemExit('usage: servermanager-discord.py <ServerManager store dir>')
    store = pathlib.Path(sys.argv[1])
    ids = read_env(CONFIG / 'discord.env')
    hooks = read_env(CONFIG / 'discord-webhooks.env')
    webhooks = []
    for route, events in ROUTES.items():
        url = hooks.get(f'DISCORD_WEBHOOK_{route}', '')
        if not url.startswith('https://discord.com/api/webhooks/'):
            raise SystemExit(f'DISCORD_WEBHOOK_{route} is missing from discord-webhooks.env')
        hook = {'name': NAMES[route], 'enabled': True, 'url': url, 'events': events, 'language': 'English'}
        if route == 'ADMIN_ALERTS':
            hook['include_steam_id'] = True
        webhooks.append(hook)
    bot = {
        'enabled': True,
        'token': '',
        'guild_ids': [snowflake(ids, 'DISCORD_GUILD_ID')],
        'admin_user_ids': [snowflake(ids, 'DISCORD_OWNER_USER_ID')],
        'admin_channel_ids': [snowflake(ids, 'DISCORD_CHANNEL_ADMIN_CONSOLE_ID')],
        'chat_channel_ids': [snowflake(ids, 'DISCORD_CHANNEL_CHAT_ID')],
    }
    # JSON is valid YAML, and ServerManager's YAML loader reads it; no YAML library on the host.
    text = ('# Generated by scripts/servermanager-discord.py from the Discord layout; do not edit.\n'
            + json.dumps({'bot': bot, 'webhooks': webhooks}, indent=2) + '\n')
    store.mkdir(parents=True, exist_ok=True)
    target = store / 'discord.yml'
    tmp = store / '.discord.yml.tmp'
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, 'w') as out:
        out.write(text)
    os.replace(tmp, target)
    print(f'discord.yml: {len(webhooks)} webhook routes, bot for one guild, one admin and one chat channel')


if __name__ == '__main__':
    main()
