#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %sWARNING: %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp "${ENV_FILE}.wizard.XXXXXX")
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sets up the Run's Discord server and gives the coding agent access to it, as described in
# docs/wiki/discord.md. Public IDs go to ~/.config/lembitu/discord.env. The two bot tokens go only
# to the macOS login keychain, typed into `security`'s own hidden prompt: they never pass through
# this script, its arguments, the shell history or the repository.

TOTAL_STAGES=7

ENV_FILE="$HOME/.config/lembitu/discord.env"
mkdir -p "$(dirname "$ENV_FILE")"
chmod 700 "$(dirname "$ENV_FILE")"

OPS_SERVICE="lembitu.discord.ops"
SERVER_BOT_SERVICE="lembitu.discord.serverbot"
# MANAGE_CHANNELS, VIEW_CHANNEL, SEND_MESSAGES, EMBED_LINKS, ATTACH_FILES, READ_MESSAGE_HISTORY,
# MANAGE_ROLES, MANAGE_WEBHOOKS, PIN_MESSAGES. No Administrator.
OPS_PERMISSIONS=2251800619109392
# VIEW_CHANNEL, SEND_MESSAGES, EMBED_LINKS, READ_MESSAGE_HISTORY.
SERVER_BOT_PERMISSIONS=84992
USER_AGENT="DiscordBot (https://github.com/rakoort/valheim-lembitu, 1)"

[[ "$(uname -s)" == "Darwin" ]] || { warn "this wizard stores tokens in the macOS keychain; run it on the Mac"; exit 1; }

# store_token SERVICE LABEL: lets `security` prompt for the token itself, hidden.
store_token() {
  local service="$1" label="$2"
  say "Paste the $label token at the 'password data' prompt below (input is hidden)."
  security add-generic-password -U -a "$USER" -s "$service" -l "$label" -w
  if security find-generic-password -a "$USER" -s "$service" >/dev/null 2>&1; then
    printf '  %s✓ stored%s %s in the login keychain\n' "$GREEN" "$RESET" "$service"
  else
    warn "the keychain has no $service entry; re-run this stage"
    exit 1
  fi
}

banner "Lembitu Discord server and agent access"

stage "Your Discord account"
say "The bot's role-managing permissions need its owner to use two-factor authentication"
say "if the server ever requires 2FA for moderation."
open_url "https://discord.com/channels/@me"
step "User Settings → My Account: enable Two-Factor Authentication if it is off."
step "User Settings → Advanced: turn on Developer Mode, so IDs can be copied."
pause "Done?"

stage "Create the Discord server"
step "In the server list, click + (Add a Server) → Create My Own → For me and my friends."
step "Name it Lembitu and create it. Leave its default channels; the agent rearranges them."
step "Right-click the server icon → Copy Server ID."
ask DISCORD_GUILD_ID "Paste the server ID:"
[[ "$DISCORD_GUILD_ID" =~ ^[0-9]{17,20}$ ]] || { warn "that is not a Discord ID"; exit 1; }
write_env DISCORD_GUILD_ID "$DISCORD_GUILD_ID"
step "Click your own name in the member list → Copy User ID."
ask DISCORD_OWNER_USER_ID "Paste your user ID:"
[[ "$DISCORD_OWNER_USER_ID" =~ ^[0-9]{17,20}$ ]] || { warn "that is not a Discord ID"; exit 1; }
write_env DISCORD_OWNER_USER_ID "$DISCORD_OWNER_USER_ID"

stage "The agent's bot: Lembitu Ops"
open_url "https://discord.com/developers/applications"
step "New Application → name it Lembitu Ops → Create."
step "General Information: copy the Application ID."
ask DISCORD_OPS_APP_ID "Paste the Lembitu Ops application ID:"
[[ "$DISCORD_OPS_APP_ID" =~ ^[0-9]{17,20}$ ]] || { warn "that is not a Discord ID"; exit 1; }
write_env DISCORD_OPS_APP_ID "$DISCORD_OPS_APP_ID"
step "Bot: turn OFF Public Bot. Leave all three Privileged Gateway Intents OFF."
step "Bot → Token → Reset Token, confirm, then Copy. It is shown once."
store_token "$OPS_SERVICE" "Lembitu Ops bot"

stage "Install Lembitu Ops on the server"
say "This invite grants channel, role, webhook and pin management, never Administrator."
open_url "https://discord.com/oauth2/authorize?client_id=${DISCORD_OPS_APP_ID}&scope=bot%20applications.commands&permissions=${OPS_PERMISSIONS}&integration_type=0&guild_id=${DISCORD_GUILD_ID}&disable_guild_select=true"
step "Check that the server is Lembitu, keep every permission ticked, Authorize."
step "Server Settings → Roles: drag the Lembitu Ops role to the top, just under your own roles."
note "A bot can manage only roles below its own highest role."
pause "Installed and moved?"

stage "The game server's bot: Lembitu Server"
say "ServerManager runs its own bot inside the game server for the chat bridge and admin commands."
open_url "https://discord.com/developers/applications"
step "New Application → name it Lembitu Server → Create; copy its Application ID."
ask DISCORD_SERVER_BOT_APP_ID "Paste the Lembitu Server application ID:"
[[ "$DISCORD_SERVER_BOT_APP_ID" =~ ^[0-9]{17,20}$ ]] || { warn "that is not a Discord ID"; exit 1; }
write_env DISCORD_SERVER_BOT_APP_ID "$DISCORD_SERVER_BOT_APP_ID"
step "Bot: turn OFF Public Bot, and turn ON Message Content Intent (the chat bridge reads messages)."
step "Bot → Token → Reset Token, confirm, then Copy."
store_token "$SERVER_BOT_SERVICE" "Lembitu Server bot"
open_url "https://discord.com/oauth2/authorize?client_id=${DISCORD_SERVER_BOT_APP_ID}&scope=bot%20applications.commands&permissions=${SERVER_BOT_PERMISSIONS}&integration_type=0&guild_id=${DISCORD_GUILD_ID}&disable_guild_select=true"
step "Authorize it on Lembitu."
pause "Installed?"

stage "Community features (optional)"
say "Community gives a rules screen and an announcement channel players can follow."
say "Enabling it needs Administrator, so you do it by hand instead of the agent."
if confirm "Enable Community now?"; then
  step "Server Settings → Enable Community → Get Started; accept the safety checks."
  step "Let Discord create #rules and #moderator-only; the agent will reuse them."
  pause "Done?"
  write_env DISCORD_COMMUNITY "enabled"
else
  write_env DISCORD_COMMUNITY "off"
fi

stage "Check the agent's access"
say "Asking Discord, with the Lembitu Ops token, who the bot is and which server it sees."
token=$(security find-generic-password -a "$USER" -s "$OPS_SERVICE" -w)
me=$(curl -fsS -H "Authorization: Bot ${token}" -H "User-Agent: ${USER_AGENT}" \
  https://discord.com/api/v10/users/@me) || { unset token; warn "Discord refused the Lembitu Ops token; reset it and re-run stage 3"; exit 1; }
guild=$(curl -fsS -H "Authorization: Bot ${token}" -H "User-Agent: ${USER_AGENT}" \
  "https://discord.com/api/v10/guilds/${DISCORD_GUILD_ID}") || { unset token; warn "the bot is not on the server; re-run stage 4"; exit 1; }
unset token
printf '  %s✓ bot%s %s\n' "$GREEN" "$RESET" "$(printf '%s' "$me" | sed -n 's/.*"username": *"\([^"]*\)".*/\1/p')"
printf '  %s✓ server%s %s\n' "$GREEN" "$RESET" "$(printf '%s' "$guild" | sed -n 's/.*"name": *"\([^"]*\)".*/\1/p' | head -n1)"
say "Tell the agent the wizard finished; it takes the setup from here."
pause

finish
