#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %sWARNING: %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp "${ENV_FILE}.wizard.XXXXXX")
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sets up astral.ee for the Run (docs/wiki/operations.md): lembitu.astral.ee points at astral-bicep
# for the game, and lembitu-map.astral.ee reaches the web map through a Cloudflare Tunnel, so no
# router port opens. Tokens are typed into the macOS keychain's own hidden prompt or come back from
# the API, and reach astral-bicep over ssh standard input; they never pass through this script's
# arguments, the shell history or the repository. Public IDs go to ~/.config/lembitu/cloudflare.env.

TOTAL_STAGES=7

ENV_FILE="$HOME/.config/lembitu/cloudflare.env"
mkdir -p "$(dirname "$ENV_FILE")"
chmod 700 "$(dirname "$ENV_FILE")"

ZONE="astral.ee"
GAME_NAME="lembitu"
MAP_NAME="lembitu-map"
TUNNEL_NAME="lembitu-map"
MAP_ORIGIN="http://127.0.0.1:3000"
GAME_HOST="astral-bicep"
TOKEN_SERVICE="lembitu.cloudflare.api"
API="https://api.cloudflare.com/client/v4"

[[ "$(uname -s)" == "Darwin" ]] || { warn "this wizard stores the token in the macOS keychain; run it on the Mac"; exit 1; }
command -v jq >/dev/null 2>&1 || { warn "jq is required"; exit 1; }

# cf METHOD PATH [JSON]: one API call; the token reaches curl on standard input, never as an argument.
cf() {
  local method=$1 path=$2 body=${3:-} token
  token=$(security find-generic-password -a "$USER" -s "$TOKEN_SERVICE" -w)
  local -a data=()
  [[ -n "$body" ]] && data=(-H "Content-Type: application/json" --data "$body")
  printf 'header = "Authorization: Bearer %s"\n' "$token" \
    | curl -sS -K - -X "$method" ${data[@]+"${data[@]}"} "$API$path"
}

# ok JSON WHAT: stop with Cloudflare's own error unless the call succeeded.
ok() { [[ "$(jq -r '.success' <<<"$1")" == true ]] || { warn "$2 failed: $(jq -c '.errors' <<<"$1")"; exit 1; }; }

# upsert_record TYPE NAME CONTENT PROXIED: create the record, or update the one already there.
upsert_record() {
  local type=$1 fqdn="$2.$ZONE" content=$3 proxied=$4 body existing id result
  body=$(jq -cn --arg t "$type" --arg n "$fqdn" --arg c "$content" --argjson p "$proxied" \
    '{type:$t,name:$n,content:$c,ttl:(if $p then 1 else 60 end),proxied:$p,comment:"Lembitu"}')
  existing=$(cf GET "/zones/$CLOUDFLARE_ZONE_ID/dns_records?name=$fqdn")
  id=$(jq -r '.result[0].id // empty' <<<"$existing")
  if [[ -n "$id" ]]; then result=$(cf PUT "/zones/$CLOUDFLARE_ZONE_ID/dns_records/$id" "$body")
  else result=$(cf POST "/zones/$CLOUDFLARE_ZONE_ID/dns_records" "$body"); fi
  ok "$result" "$fqdn"
  printf '  %s✓ %s%s → %s (%s)\n' "$GREEN" "$fqdn" "$RESET" "$content" "$([[ $proxied == true ]] && echo proxied || echo 'DNS only')"
}

stage "Create an API token"
say "One token, limited to $ZONE and to Cloudflare Tunnel, for this wizard and the address updater."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Create Custom Token. Name it 'Lembitu'."
step "Permissions (Add more for each row):"
step "  Zone · DNS · Edit"
step "  Zone · Zone · Read"
step "  Zone · Zone WAF · Edit          (the map's rate limit)"
step "  Account · Cloudflare Tunnel · Edit"
step "Zone Resources: Include · Specific zone · $ZONE.  Account Resources: Include · your account."
step "Continue to summary → Create Token, then Copy. It is shown once."
say "Paste the token at the 'password data' prompt below (input is hidden)."
security add-generic-password -U -a "$USER" -s "$TOKEN_SERVICE" -l "Lembitu Cloudflare API" -w
check=$(cf GET /user/tokens/verify)
[[ "$(jq -r '.result.status // empty' <<<"$check")" == active ]] \
  || { warn "Cloudflare does not accept that token; re-run this stage"; exit 1; }
printf '  %s✓ token active%s and stored in the keychain as %s\n' "$GREEN" "$RESET" "$TOKEN_SERVICE"

stage "Find the zone and account"
zones=$(cf GET "/zones?name=$ZONE")
CLOUDFLARE_ZONE_ID=$(jq -r '.result[0].id // empty' <<<"$zones")
CLOUDFLARE_ACCOUNT_ID=$(jq -r '.result[0].account.id // empty' <<<"$zones")
[[ -n "$CLOUDFLARE_ZONE_ID" && -n "$CLOUDFLARE_ACCOUNT_ID" ]] \
  || { warn "the token cannot see $ZONE; it needs Zone · Zone · Read for that zone"; exit 1; }
write_env CLOUDFLARE_ZONE "$ZONE"
write_env CLOUDFLARE_ZONE_ID "$CLOUDFLARE_ZONE_ID"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

stage "Point the game's name at astral-bicep"
say "Asking $GAME_HOST for its public address, so the record matches the server, not this Mac."
ip=$(ssh -o BatchMode=yes -o ConnectTimeout=8 "$GAME_HOST" "curl -s -4 --max-time 5 https://api.ipify.org" || true)
if [[ ! "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  warn "could not reach $GAME_HOST over ssh"
  ask PUBLIC_IP "Type astral-bicep's public IPv4 address:"
  ip=$PUBLIC_IP
fi
[[ "$ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || { warn "that is not an IPv4 address"; exit 1; }
note "DNS only: game traffic is UDP, which Cloudflare's free plan cannot carry."
upsert_record A "$GAME_NAME" "$ip" false
for stale in play map map.lembitu; do
  old=$(cf GET "/zones/$CLOUDFLARE_ZONE_ID/dns_records?name=$stale.$ZONE")
  old_id=$(jq -r '.result[0].id // empty' <<<"$old")
  if [[ -n "$old_id" ]] && confirm "Delete the unused $stale.$ZONE record?"; then
    cf DELETE "/zones/$CLOUDFLARE_ZONE_ID/dns_records/$old_id" >/dev/null
    printf '  %s✓ deleted%s %s.%s\n' "$GREEN" "$RESET" "$stale" "$ZONE"
  fi
done

stage "Create the map's tunnel"
say "astral-bicep connects out to Cloudflare; visitors reach the map through Cloudflare only."
tunnels=$(cf GET "/accounts/$CLOUDFLARE_ACCOUNT_ID/cfd_tunnel?name=$TUNNEL_NAME&is_deleted=false")
ok "$tunnels" "listing tunnels"
TUNNEL_ID=$(jq -r '.result[0].id // empty' <<<"$tunnels")
if [[ -z "$TUNNEL_ID" ]]; then
  created=$(cf POST "/accounts/$CLOUDFLARE_ACCOUNT_ID/cfd_tunnel" \
    "$(jq -cn --arg n "$TUNNEL_NAME" '{name:$n,config_src:"cloudflare"}')")
  ok "$created" "creating the tunnel"
  TUNNEL_ID=$(jq -r '.result.id' <<<"$created")
fi
write_env CLOUDFLARE_TUNNEL_ID "$TUNNEL_ID"
config=$(jq -cn --arg h "$MAP_NAME.$ZONE" --arg s "$MAP_ORIGIN" \
  '{config:{ingress:[{hostname:$h,service:$s},{service:"http_status:404"}]}}')
ok "$(cf PUT "/accounts/$CLOUDFLARE_ACCOUNT_ID/cfd_tunnel/$TUNNEL_ID/configurations" "$config")" "configuring the tunnel"
printf '  %s✓ tunnel%s %s sends %s.%s to %s on astral-bicep\n' "$GREEN" "$RESET" "$TUNNEL_NAME" "$MAP_NAME" "$ZONE" "$MAP_ORIGIN"
upsert_record CNAME "$MAP_NAME" "$TUNNEL_ID.cfargotunnel.com" true

stage "Rate-limit the map"
say "Cloudflare blocks any visitor sending more than 100 map requests in 10 seconds, for 10 seconds."
phase="/zones/$CLOUDFLARE_ZONE_ID/rulesets/phases/http_ratelimit/entrypoint"
current=$(cf GET "$phase")
others=$(jq '[.result.rules // [] | .[] | select(.description != "Lembitu map")] | length' <<<"$current" 2>/dev/null || echo 0)
if [[ "$others" != 0 ]]; then
  warn "the zone already has other rate-limit rules; leaving them alone and skipping this one"
  SKIPPED+=("rate-limit rule for $MAP_NAME.$ZONE (zone has other rules)")
else
  rule=$(jq -cn --arg h "$MAP_NAME.$ZONE" '{rules:[{description:"Lembitu map",
    expression:("(http.host eq \"" + $h + "\")"), action:"block",
    ratelimit:{characteristics:["cf.colo.id","ip.src"],period:10,requests_per_period:100,mitigation_timeout:10}}]}')
  result=$(cf PUT "$phase" "$rule")
  if [[ "$(jq -r '.success' <<<"$result")" == true ]]; then
    printf '  %s✓ rate limit%s on %s.%s\n' "$GREEN" "$RESET" "$MAP_NAME" "$ZONE"
  else
    warn "Cloudflare refused the rule: $(jq -c '.errors' <<<"$result")"
    SKIPPED+=("rate-limit rule for $MAP_NAME.$ZONE")
  fi
fi

stage "Give astral-bicep its two secrets"
say "The tunnel token runs the map's connection; the API token lets astral-bicep keep"
say "$GAME_NAME.$ZONE current when your home address changes. Both files are readable only by you."
if confirm "Write ~/.config/lembitu/cloudflared.env and cloudflare.env on $GAME_HOST now?"; then
  tunnel_token=$(cf GET "/accounts/$CLOUDFLARE_ACCOUNT_ID/cfd_tunnel/$TUNNEL_ID/token" | jq -r '.result // empty')
  [[ -n "$tunnel_token" ]] || { warn "Cloudflare returned no tunnel token"; exit 1; }
  { printf 'TUNNEL_TOKEN=%s\n' "$tunnel_token"; } | ssh -o BatchMode=yes "$GAME_HOST" \
      "sh -c 'umask 077; mkdir -p ~/.config/lembitu && cat > ~/.config/lembitu/cloudflared.env'" \
    || { warn "copy failed"; exit 1; }
  unset tunnel_token
  { printf 'CLOUDFLARE_API_TOKEN=%s\n' "$(security find-generic-password -a "$USER" -s "$TOKEN_SERVICE" -w)"
    printf 'CLOUDFLARE_ZONE=%s\nCLOUDFLARE_ZONE_ID=%s\nCLOUDFLARE_RECORDS=%s\n' "$ZONE" "$CLOUDFLARE_ZONE_ID" "$GAME_NAME"
  } | ssh -o BatchMode=yes "$GAME_HOST" \
      "sh -c 'umask 077; cat > ~/.config/lembitu/cloudflare.env'" \
    || { warn "copy failed"; exit 1; }
  printf '  %s✓ written%s on %s\n' "$GREEN" "$RESET" "$GAME_HOST"
else
  SKIPPED+=("copy the tunnel and API tokens to $GAME_HOST (re-run and accept this stage)")
fi

stage "Check"
got=$(dig +short "$GAME_NAME.$ZONE" @1.1.1.1 | tail -n 1)
if [[ "$got" == "$ip" ]]; then printf '  %s✓ %s.%s%s resolves to %s\n' "$GREEN" "$GAME_NAME" "$ZONE" "$RESET" "$got"
else warn "$GAME_NAME.$ZONE resolves to '${got:-nothing}' yet; Cloudflare usually updates within a minute"; fi
map_ip=$(dig +short "$MAP_NAME.$ZONE" @1.1.1.1 | tail -n 1)
if [[ -n "$map_ip" && "$map_ip" != "$ip" ]]; then
  printf '  %s✓ %s.%s%s resolves to Cloudflare (%s), not your home address\n' "$GREEN" "$MAP_NAME" "$ZONE" "$RESET" "$map_ip"
else warn "$MAP_NAME.$ZONE resolves to '${map_ip:-nothing}' yet"; fi
say "No router port needs opening. If you already forwarded TCP 80 or 443, remove those forwards."
say "Tell the agent the wizard finished; it starts the tunnel and the address updater on astral-bicep."
pause

finish
